export enum TOOLS_APP_ROUTES {
    HOME = "/",
    ADD_ADVERTS = "/add-adverts",
    LOGIN = "/login",
    PROFILE = "/profile",
    MESSAGES = "/profile/messages",
    MY_ADVERTS = "/profile/my-adverts",
    FAVOURITES = "/profile/favourites",
    RENTED_TOOLS = "/profile/rentedt-tools",
    HELP = "/help",
    ADVERTISING = "/advertising",
    ABOUT_US = "/about-us",
    CONTACTS = "/contacts",
    PRIVACY_POLICY = "privacyp-olicy",
    CONDITIONS = "/conditions",
    IMPRINT = "/imprint",
    SOCIAL_MEDIA = "/medias",
    NOT_FOUND = "*",
  }
  